export type MenuItem = {
  id: string;
  name: string;
  description: string;
  price: number;
  category: string;
};

export type Restaurant = {
  id: string;
  name: string;
  description: string;
  image: string;
  rating: number;
  cuisine: string[];
  menu: MenuItem[];
};

export const restaurants: Restaurant[] = [
  {
    id: '1',
    name: 'Saffron Spice',
    description: 'Authentic Indian cuisine with a modern twist.',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&h=600&fit=crop&crop=center',
    rating: 4.7,
    cuisine: ['Indian', 'Vegetarian', 'Spicy'],
    menu: [
      { id: '1-1', name: 'Butter Chicken', description: 'Creamy tomato-based chicken curry.', price: 14.99, category: 'Main Course' },
      { id: '1-2', name: 'Paneer Tikka', description: 'Grilled cottage cheese with spices.', price: 11.99, category: 'Appetizer' },
      { id: '1-3', name: 'Garlic Naan', description: 'Soft naan bread topped with garlic.', price: 3.99, category: 'Bread' },
      { id: '1-4', name: 'Chicken Biryani', description: 'Spiced rice with marinated chicken.', price: 13.99, category: 'Main Course' },
      { id: '1-5', name: 'Dal Makhani', description: 'Slow-cooked black lentils.', price: 9.99, category: 'Main Course' },
      { id: '1-6', name: 'Samosa', description: 'Crispy pastry with spiced potatoes.', price: 4.99, category: 'Appetizer' },
      { id: '1-7', name: 'Tandoori Chicken', description: 'Chicken marinated in yogurt and spices.', price: 12.99, category: 'Main Course' },
      { id: '1-8', name: 'Aloo Gobi', description: 'Potato and cauliflower curry.', price: 8.99, category: 'Main Course' },
      { id: '1-9', name: 'Raita', description: 'Yogurt with cucumber and spices.', price: 2.99, category: 'Side' },
      { id: '1-10', name: 'Gulab Jamun', description: 'Sweet milk-solid dessert.', price: 5.49, category: 'Dessert' },
    ],
  },
  {
    id: '2',
    name: 'Tokyo Table',
    description: 'Fresh sushi and Japanese classics.',
    image: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800&h=600&fit=crop&crop=center',
    rating: 4.8,
    cuisine: ['Japanese', 'Sushi', 'Seafood'],
    menu: [
      { id: '2-1', name: 'Salmon Nigiri', description: 'Sushi rice topped with fresh salmon.', price: 8.99, category: 'Sushi' },
      { id: '2-2', name: 'Chicken Katsu', description: 'Breaded chicken cutlet with tonkatsu sauce.', price: 12.99, category: 'Main Course' },
      { id: '2-3', name: 'Miso Soup', description: 'Traditional Japanese soup with tofu and seaweed.', price: 2.99, category: 'Soup' },
      { id: '2-4', name: 'California Roll', description: 'Crab, avocado, and cucumber roll.', price: 7.99, category: 'Sushi' },
      { id: '2-5', name: 'Tempura Udon', description: 'Udon noodles with tempura shrimp.', price: 13.99, category: 'Noodles' },
      { id: '2-6', name: 'Edamame', description: 'Steamed soybeans with sea salt.', price: 4.49, category: 'Appetizer' },
      { id: '2-7', name: 'Tuna Sashimi', description: 'Slices of fresh tuna.', price: 10.99, category: 'Sashimi' },
      { id: '2-8', name: 'Gyoza', description: 'Pan-fried Japanese dumplings.', price: 6.99, category: 'Appetizer' },
      { id: '2-9', name: 'Teriyaki Chicken', description: 'Chicken glazed with teriyaki sauce.', price: 11.99, category: 'Main Course' },
      { id: '2-10', name: 'Green Tea Ice Cream', description: 'Japanese-style green tea ice cream.', price: 4.99, category: 'Dessert' },
    ],
  },
  {
    id: '3',
    name: 'La Bella Italia',
    description: 'Classic Italian dishes and wood-fired pizzas.',
    image: 'https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?w=800&h=600&fit=crop&crop=center',
    rating: 4.6,
    cuisine: ['Italian', 'Pizza', 'Pasta'],
    menu: [
      { id: '3-1', name: 'Margherita Pizza', description: 'Tomato, mozzarella, and basil.', price: 13.99, category: 'Pizza' },
      { id: '3-2', name: 'Spaghetti Carbonara', description: 'Pasta with pancetta, egg, and parmesan.', price: 15.99, category: 'Pasta' },
      { id: '3-3', name: 'Tiramisu', description: 'Coffee-flavored Italian dessert.', price: 6.99, category: 'Dessert' },
      { id: '3-4', name: 'Lasagna', description: 'Layered pasta with meat and cheese.', price: 14.99, category: 'Pasta' },
      { id: '3-5', name: 'Bruschetta', description: 'Grilled bread with tomato and basil.', price: 7.99, category: 'Appetizer' },
      { id: '3-6', name: 'Fettuccine Alfredo', description: 'Pasta in creamy Alfredo sauce.', price: 13.99, category: 'Pasta' },
      { id: '3-7', name: 'Caprese Salad', description: 'Tomato, mozzarella, and basil salad.', price: 8.99, category: 'Salad' },
      { id: '3-8', name: 'Minestrone Soup', description: 'Hearty vegetable soup.', price: 6.49, category: 'Soup' },
      { id: '3-9', name: 'Prosciutto e Melone', description: 'Cured ham with melon.', price: 9.99, category: 'Appetizer' },
      { id: '3-10', name: 'Panna Cotta', description: 'Creamy Italian dessert.', price: 5.99, category: 'Dessert' },
    ],
  },
  {
    id: '4',
    name: 'Green Bowl',
    description: 'Healthy salads and vegan bowls.',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=600&fit=crop&crop=center',
    rating: 4.5,
    cuisine: ['Vegan', 'Healthy', 'Salads'],
    menu: [
      { id: '4-1', name: 'Quinoa Power Bowl', description: 'Quinoa, chickpeas, avocado, and greens.', price: 10.99, category: 'Bowl' },
      { id: '4-2', name: 'Caesar Salad', description: 'Romaine, croutons, and vegan Caesar dressing.', price: 9.99, category: 'Salad' },
      { id: '4-3', name: 'Avocado Toast', description: 'Sourdough with smashed avocado and seeds.', price: 7.99, category: 'Breakfast' },
      { id: '4-4', name: 'Sweet Potato Bowl', description: 'Roasted sweet potatoes, kale, and tahini.', price: 11.49, category: 'Bowl' },
      { id: '4-5', name: 'Lentil Soup', description: 'Hearty lentil and vegetable soup.', price: 6.99, category: 'Soup' },
      { id: '4-6', name: 'Falafel Salad', description: 'Falafel balls on mixed greens.', price: 9.49, category: 'Salad' },
      { id: '4-7', name: 'Berry Smoothie', description: 'Mixed berry and banana smoothie.', price: 5.99, category: 'Drink' },
      { id: '4-8', name: 'Tofu Stir Fry', description: 'Tofu and veggies in soy sauce.', price: 10.49, category: 'Main Course' },
      { id: '4-9', name: 'Chia Pudding', description: 'Chia seeds soaked in almond milk.', price: 4.99, category: 'Dessert' },
      { id: '4-10', name: 'Hummus Plate', description: 'Hummus with veggies and pita.', price: 7.49, category: 'Appetizer' },
    ],
  },
  {
    id: '5',
    name: 'Burger Joint',
    description: 'Juicy burgers and crispy fries.',
    image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=800&h=600&fit=crop&crop=center',
    rating: 4.3,
    cuisine: ['American', 'Burgers', 'Fast Food'],
    menu: [
      { id: '5-1', name: 'Classic Cheeseburger', description: 'Beef patty, cheddar, lettuce, tomato, onion.', price: 11.99, category: 'Burger' },
      { id: '5-2', name: 'Crispy Fries', description: 'Golden, crispy French fries.', price: 3.99, category: 'Sides' },
      { id: '5-3', name: 'Veggie Burger', description: 'Grilled veggie patty with toppings.', price: 10.99, category: 'Burger' },
      { id: '5-4', name: 'Chicken Sandwich', description: 'Fried chicken breast with pickles.', price: 9.99, category: 'Sandwich' },
      { id: '5-5', name: 'Onion Rings', description: 'Crispy battered onion rings.', price: 4.99, category: 'Sides' },
      { id: '5-6', name: 'Milkshake', description: 'Classic vanilla milkshake.', price: 5.49, category: 'Drink' },
      { id: '5-7', name: 'Bacon Burger', description: 'Beef patty with bacon and cheese.', price: 12.99, category: 'Burger' },
      { id: '5-8', name: 'Chicken Nuggets', description: 'Breaded chicken pieces.', price: 6.99, category: 'Sides' },
      { id: '5-9', name: 'Coleslaw', description: 'Creamy cabbage slaw.', price: 3.49, category: 'Side' },
      { id: '5-10', name: 'Apple Pie', description: 'Classic American apple pie.', price: 4.99, category: 'Dessert' },
    ],
  },
  {
    id: '6',
    name: 'Dragon Wok',
    description: 'Chinese takeout favorites and dim sum.',
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=800&h=600&fit=crop&crop=center',
    rating: 4.4,
    cuisine: ['Chinese', 'Dim Sum', 'Noodles'],
    menu: [
      { id: '6-1', name: 'Kung Pao Chicken', description: 'Spicy stir-fried chicken with peanuts.', price: 13.49, category: 'Main Course' },
      { id: '6-2', name: 'Vegetable Spring Rolls', description: 'Crispy rolls with mixed veggies.', price: 5.99, category: 'Appetizer' },
      { id: '6-3', name: 'Shrimp Fried Rice', description: 'Fried rice with shrimp and vegetables.', price: 12.49, category: 'Rice' },
      { id: '6-4', name: 'Sweet and Sour Pork', description: 'Pork in sweet and sour sauce.', price: 11.99, category: 'Main Course' },
      { id: '6-5', name: 'Egg Drop Soup', description: 'Egg ribbons in chicken broth.', price: 4.99, category: 'Soup' },
      { id: '6-6', name: 'Beef Chow Mein', description: 'Stir-fried noodles with beef.', price: 13.99, category: 'Noodles' },
      { id: '6-7', name: 'Mapo Tofu', description: 'Spicy tofu with minced pork.', price: 10.99, category: 'Main Course' },
      { id: '6-8', name: 'Steamed Dumplings', description: 'Pork and veggie dumplings.', price: 7.99, category: 'Appetizer' },
      { id: '6-9', name: 'Hot and Sour Soup', description: 'Spicy and tangy soup.', price: 5.49, category: 'Soup' },
      { id: '6-10', name: 'Sesame Balls', description: 'Sweet rice balls with sesame.', price: 4.99, category: 'Dessert' },
    ],
  },
  {
    id: '7',
    name: 'Taco Fiesta',
    description: 'Mexican street food and tacos.',
    image: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=800&h=600&fit=crop&crop=center',
    rating: 4.2,
    cuisine: ['Mexican', 'Tacos', 'Street Food'],
    menu: [
      { id: '7-1', name: 'Carne Asada Taco', description: 'Grilled steak, onions, cilantro, salsa.', price: 4.99, category: 'Taco' },
      { id: '7-2', name: 'Chicken Quesadilla', description: 'Grilled tortilla with cheese and chicken.', price: 8.99, category: 'Quesadilla' },
      { id: '7-3', name: 'Churros', description: 'Fried dough pastry with cinnamon sugar.', price: 5.49, category: 'Dessert' },
      { id: '7-4', name: 'Fish Taco', description: 'Battered fish, cabbage slaw, chipotle mayo.', price: 5.99, category: 'Taco' },
      { id: '7-5', name: 'Elote', description: 'Mexican street corn with cheese.', price: 4.49, category: 'Appetizer' },
      { id: '7-6', name: 'Guacamole', description: 'Avocado dip with chips.', price: 6.99, category: 'Appetizer' },
      { id: '7-7', name: 'Al Pastor Taco', description: 'Pork, pineapple, onions, cilantro.', price: 4.99, category: 'Taco' },
      { id: '7-8', name: 'Beef Burrito', description: 'Flour tortilla with beef and beans.', price: 9.99, category: 'Burrito' },
      { id: '7-9', name: 'Salsa Roja', description: 'Spicy red salsa.', price: 2.99, category: 'Side' },
      { id: '7-10', name: 'Tres Leches Cake', description: 'Moist sponge cake with three milks.', price: 6.49, category: 'Dessert' },
    ],
  },
  {
    id: '8',
    name: 'Parisian Café',
    description: 'French bistro classics and pastries.',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&h=600&fit=crop&crop=center',
    rating: 4.6,
    cuisine: ['French', 'Cafe', 'Pastries'],
    menu: [
      { id: '8-1', name: 'Croissant', description: 'Buttery, flaky French pastry.', price: 3.49, category: 'Pastry' },
      { id: '8-2', name: 'Quiche Lorraine', description: 'Savory tart with bacon and cheese.', price: 9.99, category: 'Main Course' },
      { id: '8-3', name: 'Crème Brûlée', description: 'Rich custard with caramelized sugar top.', price: 7.99, category: 'Dessert' },
      { id: '8-4', name: 'French Onion Soup', description: 'Caramelized onions, beef broth, cheese.', price: 8.49, category: 'Soup' },
      { id: '8-5', name: 'Nicoise Salad', description: 'Salad with tuna, eggs, olives.', price: 10.99, category: 'Salad' },
      { id: '8-6', name: 'Pain au Chocolat', description: 'Chocolate-filled pastry.', price: 4.49, category: 'Pastry' },
      { id: '8-7', name: 'Ratatouille', description: 'Stewed vegetables in tomato sauce.', price: 11.49, category: 'Main Course' },
      { id: '8-8', name: 'Duck Confit', description: 'Slow-cooked duck leg.', price: 15.99, category: 'Main Course' },
      { id: '8-9', name: 'Madeleine', description: 'Small shell-shaped sponge cake.', price: 3.99, category: 'Dessert' },
      { id: '8-10', name: 'Macaron', description: 'French meringue-based cookie.', price: 2.99, category: 'Dessert' },
    ],
  },
  {
    id: '9',
    name: 'Mediterraneo',
    description: 'Mediterranean flavors and mezze plates.',
    image: 'https://images.unsplash.com/photo-1544148103-0773bf10d330?w=800&h=600&fit=crop&crop=center',
    rating: 4.5,
    cuisine: ['Mediterranean', 'Greek', 'Healthy'],
    menu: [
      { id: '9-1', name: 'Falafel Wrap', description: 'Chickpea fritters, veggies, tahini sauce.', price: 8.49, category: 'Wrap' },
      { id: '9-2', name: 'Greek Salad', description: 'Tomato, cucumber, feta, olives.', price: 7.99, category: 'Salad' },
      { id: '9-3', name: 'Baklava', description: 'Sweet pastry with nuts and honey.', price: 5.99, category: 'Dessert' },
      { id: '9-4', name: 'Hummus', description: 'Chickpea dip with olive oil.', price: 6.49, category: 'Appetizer' },
      { id: '9-5', name: 'Lamb Gyro', description: 'Sliced lamb in pita bread.', price: 10.99, category: 'Wrap' },
      { id: '9-6', name: 'Spanakopita', description: 'Spinach and feta pastry.', price: 7.49, category: 'Appetizer' },
      { id: '9-7', name: 'Tabbouleh', description: 'Parsley, tomato, and bulgur salad.', price: 6.99, category: 'Salad' },
      { id: '9-8', name: 'Chicken Souvlaki', description: 'Grilled chicken skewers.', price: 11.99, category: 'Main Course' },
      { id: '9-9', name: 'Dolma', description: 'Stuffed grape leaves.', price: 5.49, category: 'Appetizer' },
      { id: '9-10', name: 'Rice Pudding', description: 'Creamy rice dessert.', price: 4.99, category: 'Dessert' },
    ],
  },
  {
    id: '10',
    name: 'Urban Deli',
    description: 'Sandwiches, soups, and quick bites.',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&h=600&fit=crop&crop=center',
    rating: 4.1,
    cuisine: ['Deli', 'Sandwiches', 'Quick Bites'],
    menu: [
      { id: '10-1', name: 'Turkey Club', description: 'Triple-decker with turkey, bacon, lettuce, tomato.', price: 10.49, category: 'Sandwich' },
      { id: '10-2', name: 'Tomato Basil Soup', description: 'Creamy tomato soup with basil.', price: 5.49, category: 'Soup' },
      { id: '10-3', name: 'Chocolate Chip Cookie', description: 'Freshly baked, gooey chocolate chip cookie.', price: 2.49, category: 'Dessert' },
      { id: '10-4', name: 'BLT Sandwich', description: 'Bacon, lettuce, and tomato sandwich.', price: 8.99, category: 'Sandwich' },
      { id: '10-5', name: 'Chicken Caesar Wrap', description: 'Grilled chicken, romaine, Caesar dressing.', price: 9.99, category: 'Wrap' },
      { id: '10-6', name: 'Potato Chips', description: 'Crispy house-made chips.', price: 2.99, category: 'Sides' },
      { id: '10-7', name: 'Egg Salad Sandwich', description: 'Egg salad on whole wheat.', price: 7.49, category: 'Sandwich' },
      { id: '10-8', name: 'Roast Beef Panini', description: 'Roast beef, cheese, grilled bread.', price: 11.49, category: 'Sandwich' },
      { id: '10-9', name: 'Lentil Soup', description: 'Hearty lentil and vegetable soup.', price: 5.99, category: 'Soup' },
      { id: '10-10', name: 'Brownie', description: 'Rich chocolate brownie.', price: 3.49, category: 'Dessert' },
    ],
  },
  {
    id: '11',
    name: 'Seoul Kitchen',
    description: 'Authentic Korean BBQ and traditional dishes.',
    image: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800&h=600&fit=crop&crop=center',
    rating: 4.7,
    cuisine: ['Korean', 'BBQ', 'Asian'],
    menu: [
      { id: '11-1', name: 'Bulgogi', description: 'Marinated beef BBQ with vegetables.', price: 15.99, category: 'Main Course' },
      { id: '11-2', name: 'Kimchi Fried Rice', description: 'Spicy fermented cabbage fried rice.', price: 10.99, category: 'Rice' },
      { id: '11-3', name: 'Bibimbap', description: 'Mixed rice with vegetables and meat.', price: 12.49, category: 'Rice Bowl' },
      { id: '11-4', name: 'Korean Fried Chicken', description: 'Crispy chicken with sweet soy glaze.', price: 13.99, category: 'Main Course' },
      { id: '11-5', name: 'Japchae', description: 'Sweet potato starch noodles with vegetables.', price: 9.99, category: 'Noodles' },
      { id: '11-6', name: 'Kimchi', description: 'Traditional fermented vegetable side dish.', price: 4.99, category: 'Side' },
      { id: '11-7', name: 'Korean Corn Dogs', description: 'Mozzarella-filled corn dogs.', price: 6.99, category: 'Appetizer' },
      { id: '11-8', name: 'Galbi', description: 'Grilled short ribs.', price: 18.99, category: 'Main Course' },
      { id: '11-9', name: 'Miso Soup', description: 'Traditional soybean paste soup.', price: 3.99, category: 'Soup' },
      { id: '11-10', name: 'Korean Shaved Ice', description: 'Sweet shaved ice with toppings.', price: 7.99, category: 'Dessert' },
    ],
  },
  {
    id: '12',
    name: 'Mumbai Express',
    description: 'Spicy Indian street food and curries.',
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=800&h=600&fit=crop&crop=center',
    rating: 4.6,
    cuisine: ['Indian', 'Street Food', 'Spicy'],
    menu: [
      { id: '12-1', name: 'Pav Bhaji', description: 'Spicy vegetable curry with bread rolls.', price: 8.99, category: 'Street Food' },
      { id: '12-2', name: 'Vada Pav', description: 'Fried potato dumpling burger.', price: 5.99, category: 'Street Food' },
      { id: '12-3', name: 'Dosa', description: 'Crispy rice and lentil crepe.', price: 9.49, category: 'Main Course' },
      { id: '12-4', name: 'Chole Bhature', description: 'Spicy chickpeas with fried bread.', price: 10.99, category: 'Main Course' },
      { id: '12-5', name: 'Mango Lassi', description: 'Sweet yogurt drink with mango.', price: 4.49, category: 'Drink' },
      { id: '12-6', name: 'Bhel Puri', description: 'Crunchy puffed rice snack mix.', price: 6.99, category: 'Street Food' },
      { id: '12-7', name: 'Fish Curry', description: 'Coconut-based fish curry.', price: 14.99, category: 'Main Course' },
      { id: '12-8', name: 'Idli Sambar', description: 'Steamed rice cakes with lentil soup.', price: 7.99, category: 'Breakfast' },
      { id: '12-9', name: 'Kulfi', description: 'Traditional Indian ice cream.', price: 4.99, category: 'Dessert' },
      { id: '12-10', name: 'Masala Chai', description: 'Spiced Indian tea.', price: 2.99, category: 'Drink' },
    ],
  },
  {
    id: '13',
    name: 'Bangkok Bites',
    description: 'Authentic Thai cuisine with bold flavors.',
    image: 'https://images.unsplash.com/photo-1559847844-5315695dadae?w=800&h=600&fit=crop&crop=center',
    rating: 4.8,
    cuisine: ['Thai', 'Spicy', 'Asian'],
    menu: [
      { id: '13-1', name: 'Pad Thai', description: 'Stir-fried rice noodles with tamarind sauce.', price: 11.99, category: 'Noodles' },
      { id: '13-2', name: 'Green Curry', description: 'Spicy coconut curry with basil.', price: 13.49, category: 'Curry' },
      { id: '13-3', name: 'Tom Yum Soup', description: 'Spicy and sour Thai soup.', price: 7.99, category: 'Soup' },
      { id: '13-4', name: 'Mango Sticky Rice', description: 'Sweet sticky rice with fresh mango.', price: 6.99, category: 'Dessert' },
      { id: '13-5', name: 'Som Tam', description: 'Spicy green papaya salad.', price: 8.49, category: 'Salad' },
      { id: '13-6', name: 'Massaman Curry', description: 'Rich curry with peanuts and potatoes.', price: 14.99, category: 'Curry' },
      { id: '13-7', name: 'Spring Rolls', description: 'Fresh vegetables wrapped in rice paper.', price: 5.99, category: 'Appetizer' },
      { id: '13-8', name: 'Thai Fried Rice', description: 'Jasmine rice stir-fried with vegetables.', price: 10.49, category: 'Rice' },
      { id: '13-9', name: 'Satay Chicken', description: 'Grilled chicken skewers with peanut sauce.', price: 9.99, category: 'Appetizer' },
      { id: '13-10', name: 'Thai Iced Tea', description: 'Sweet and creamy Thai tea.', price: 3.99, category: 'Drink' },
    ],
  },
  {
    id: '14',
    name: 'Lima Heights',
    description: 'Peruvian cuisine with fresh ceviche and bold flavors.',
    image: 'https://images.unsplash.com/photo-1551218372-a8789b81b253?w=800&h=600&fit=crop&crop=center',
    rating: 4.5,
    cuisine: ['Peruvian', 'Seafood', 'South American'],
    menu: [
      { id: '14-1', name: 'Ceviche', description: 'Fresh fish marinated in lime juice.', price: 14.99, category: 'Seafood' },
      { id: '14-2', name: 'Lomo Saltado', description: 'Stir-fried beef with onions and tomatoes.', price: 16.99, category: 'Main Course' },
      { id: '14-3', name: 'Ají de Gallina', description: 'Creamy chicken in yellow chili sauce.', price: 13.99, category: 'Main Course' },
      { id: '14-4', name: 'Anticuchos', description: 'Grilled beef heart skewers.', price: 9.99, category: 'Appetizer' },
      { id: '14-5', name: 'Papa Rellena', description: 'Stuffed potato with meat filling.', price: 6.99, category: 'Appetizer' },
      { id: '14-6', name: 'Quinoa Salad', description: 'Nutritious quinoa with vegetables.', price: 8.99, category: 'Salad' },
      { id: '14-7', name: 'Pisco Sour', description: 'Traditional Peruvian cocktail.', price: 7.99, category: 'Drink' },
      { id: '14-8', name: 'Causa Limeña', description: 'Layered potato dish with tuna.', price: 10.99, category: 'Appetizer' },
      { id: '14-9', name: 'Arroz con Pollo', description: 'Peruvian chicken and rice dish.', price: 12.99, category: 'Main Course' },
      { id: '14-10', name: 'Suspiro Limeño', description: 'Sweet caramel dessert.', price: 5.99, category: 'Dessert' },
    ],
  },
  {
    id: '15',
    name: 'Atlas Moroccan',
    description: 'North African tagines and aromatic spices.',
    image: 'https://images.unsplash.com/photo-1548943487-a2e4e43b4853?w=800&h=600&fit=crop&crop=center',
    rating: 4.4,
    cuisine: ['Moroccan', 'North African', 'Halal'],
    menu: [
      { id: '15-1', name: 'Chicken Tagine', description: 'Slow-cooked chicken with olives and preserved lemons.', price: 15.99, category: 'Main Course' },
      { id: '15-2', name: 'Lamb Couscous', description: 'Tender lamb with fluffy couscous.', price: 17.99, category: 'Main Course' },
      { id: '15-3', name: 'Moroccan Tea', description: 'Sweet mint tea served traditionally.', price: 3.49, category: 'Drink' },
      { id: '15-4', name: 'Pastilla', description: 'Sweet and savory pastry with chicken.', price: 12.99, category: 'Appetizer' },
      { id: '15-5', name: 'Harira Soup', description: 'Traditional tomato and lentil soup.', price: 6.99, category: 'Soup' },
      { id: '15-6', name: 'Zaalouk', description: 'Smoky eggplant and tomato salad.', price: 7.49, category: 'Salad' },
      { id: '15-7', name: 'Mechoui', description: 'Slow-roasted lamb shoulder.', price: 19.99, category: 'Main Course' },
      { id: '15-8', name: 'Briouats', description: 'Crispy triangular pastries with cheese.', price: 8.99, category: 'Appetizer' },
      { id: '15-9', name: 'Fruit Salad', description: 'Fresh seasonal fruits with orange blossom.', price: 5.99, category: 'Dessert' },
      { id: '15-10', name: 'Baklava', description: 'Honey-sweetened phyllo pastry.', price: 4.99, category: 'Dessert' },
    ],
  },
  {
    id: '16',
    name: 'Maple & Smoke',
    description: 'Canadian comfort food and BBQ specialties.',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&h=600&fit=crop&crop=center',
    rating: 4.3,
    cuisine: ['Canadian', 'BBQ', 'Comfort Food'],
    menu: [
      { id: '16-1', name: 'Poutine', description: 'Fries with gravy and cheese curds.', price: 8.99, category: 'Appetizer' },
      { id: '16-2', name: 'Maple Glazed Salmon', description: 'Atlantic salmon with maple glaze.', price: 18.99, category: 'Main Course' },
      { id: '16-3', name: 'Butter Tart', description: 'Traditional Canadian sweet pastry.', price: 4.49, category: 'Dessert' },
      { id: '16-4', name: 'Tourtière', description: 'Meat pie with spiced ground pork.', price: 12.99, category: 'Main Course' },
      { id: '16-5', name: 'Smoked Brisket', description: 'Slow-smoked beef brisket.', price: 16.99, category: 'Main Course' },
      { id: '16-6', name: 'Montreal Bagel', description: 'Wood-fired bagel with cream cheese.', price: 5.99, category: 'Breakfast' },
      { id: '16-7', name: 'Maple Syrup Wings', description: 'Chicken wings glazed with maple syrup.', price: 10.99, category: 'Appetizer' },
      { id: '16-8', name: 'Split Pea Soup', description: 'Hearty soup with ham and peas.', price: 6.49, category: 'Soup' },
      { id: '16-9', name: 'Nanaimo Bar', description: 'No-bake chocolate layered dessert.', price: 3.99, category: 'Dessert' },
      { id: '16-10', name: 'Caesar Cocktail', description: 'Canadian cocktail with clamato juice.', price: 6.99, category: 'Drink' },
    ],
  },
  {
    id: '17',
    name: 'Ethiopian Highlands',
    description: 'Traditional Ethiopian cuisine with injera bread.',
    image: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=800&h=600&fit=crop&crop=center',
    rating: 4.6,
    cuisine: ['Ethiopian', 'African', 'Vegetarian'],
    menu: [
      { id: '17-1', name: 'Doro Wat', description: 'Spicy chicken stew with boiled eggs.', price: 14.99, category: 'Main Course' },
      { id: '17-2', name: 'Vegetarian Combo', description: 'Mixed vegetarian dishes on injera.', price: 12.99, category: 'Vegetarian' },
      { id: '17-3', name: 'Injera Bread', description: 'Spongy sourdough flatbread.', price: 3.99, category: 'Bread' },
      { id: '17-4', name: 'Kitfo', description: 'Ethiopian-style steak tartare.', price: 16.99, category: 'Main Course' },
      { id: '17-5', name: 'Shiro', description: 'Ground chickpea stew.', price: 9.99, category: 'Vegetarian' },
      { id: '17-6', name: 'Tibs', description: 'Sautéed beef with onions and peppers.', price: 15.99, category: 'Main Course' },
      { id: '17-7', name: 'Ethiopian Honey Wine', description: 'Traditional fermented honey beverage.', price: 8.99, category: 'Drink' },
      { id: '17-8', name: 'Gomen', description: 'Collard greens with garlic and ginger.', price: 7.99, category: 'Vegetarian' },
      { id: '17-9', name: 'Ethiopian Coffee', description: 'Traditional coffee ceremony brew.', price: 4.49, category: 'Drink' },
      { id: '17-10', name: 'Sambusa', description: 'Fried pastry with meat or lentil filling.', price: 5.99, category: 'Appetizer' },
    ],
  },
  {
    id: '18',
    name: 'Viking Feast',
    description: 'Scandinavian cuisine with Nordic flavors.',
    image: 'https://images.unsplash.com/photo-1551218372-a8789b81b253?w=800&h=600&fit=crop&crop=center',
    rating: 4.5,
    cuisine: ['Scandinavian', 'Nordic', 'Seafood'],
    menu: [
      { id: '18-1', name: 'Gravlax', description: 'Cured salmon with dill and mustard sauce.', price: 13.99, category: 'Appetizer' },
      { id: '18-2', name: 'Swedish Meatballs', description: 'Traditional meatballs with lingonberry sauce.', price: 12.99, category: 'Main Course' },
      { id: '18-3', name: 'Reindeer Steak', description: 'Lean reindeer meat with juniper berries.', price: 22.99, category: 'Main Course' },
      { id: '18-4', name: 'Smørrebrød', description: 'Open-faced sandwich with toppings.', price: 9.99, category: 'Sandwich' },
      { id: '18-5', name: 'Fish Soup', description: 'Creamy Nordic fish and potato soup.', price: 8.99, category: 'Soup' },
      { id: '18-6', name: 'Cloudberry Jam', description: 'Arctic cloudberry preserve.', price: 4.99, category: 'Side' },
      { id: '18-7', name: 'Aquavit', description: 'Traditional Scandinavian spirit.', price: 7.99, category: 'Drink' },
      { id: '18-8', name: 'Rye Bread', description: 'Dense, dark Scandinavian rye bread.', price: 3.49, category: 'Bread' },
      { id: '18-9', name: 'Princess Cake', description: 'Swedish layered cake with marzipan.', price: 6.99, category: 'Dessert' },
      { id: '18-10', name: 'Glögg', description: 'Spiced mulled wine with almonds.', price: 5.99, category: 'Drink' },
    ],
  },
  {
    id: '19',
    name: 'Outback Grill',
    description: 'Australian BBQ and pub favorites.',
    image: 'https://images.unsplash.com/photo-1558030006-450675393462?w=800&h=600&fit=crop&crop=center',
    rating: 4.2,
    cuisine: ['Australian', 'BBQ', 'Pub Food'],
    menu: [
      { id: '19-1', name: 'Kangaroo Steak', description: 'Lean kangaroo meat with native spices.', price: 19.99, category: 'Main Course' },
      { id: '19-2', name: 'Meat Pie', description: 'Flaky pastry filled with minced meat.', price: 8.99, category: 'Main Course' },
      { id: '19-3', name: 'Lamington', description: 'Sponge cake covered in chocolate and coconut.', price: 4.99, category: 'Dessert' },
      { id: '19-4', name: 'Barramundi', description: 'Grilled Australian fish with lemon myrtle.', price: 17.99, category: 'Seafood' },
      { id: '19-5', name: 'Pavlova', description: 'Meringue dessert with cream and fruit.', price: 6.99, category: 'Dessert' },
      { id: '19-6', name: 'Damper Bread', description: 'Traditional bush bread.', price: 4.49, category: 'Bread' },
      { id: '19-7', name: 'Vegemite Toast', description: 'Toast with iconic Australian spread.', price: 3.99, category: 'Breakfast' },
      { id: '19-8', name: 'BBQ Prawns', description: 'Grilled prawns with garlic butter.', price: 15.99, category: 'Seafood' },
      { id: '19-9', name: 'Australian Beer', description: 'Local craft beer selection.', price: 5.99, category: 'Drink' },
      { id: '19-10', name: 'Tim Tam Cheesecake', description: 'Cheesecake with chocolate biscuits.', price: 7.49, category: 'Dessert' },
    ],
  },
  {
    id: '20',
    name: 'Beirut Express',
    description: 'Lebanese mezze and grilled specialties.',
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800&h=600&fit=crop&crop=center',
    rating: 4.7,
    cuisine: ['Lebanese', 'Middle Eastern', 'Halal'],
    menu: [
      { id: '20-1', name: 'Shawarma', description: 'Marinated meat in pita with garlic sauce.', price: 9.99, category: 'Wrap' },
      { id: '20-2', name: 'Mezze Platter', description: 'Selection of small Lebanese dishes.', price: 18.99, category: 'Appetizer' },
      { id: '20-3', name: 'Baklava', description: 'Phyllo pastry with nuts and honey.', price: 5.49, category: 'Dessert' },
      { id: '20-4', name: 'Tabbouleh', description: 'Parsley salad with tomato and bulgur.', price: 7.99, category: 'Salad' },
      { id: '20-5', name: 'Kibbeh', description: 'Fried bulgur and meat croquettes.', price: 8.99, category: 'Appetizer' },
      { id: '20-6', name: 'Fattoush', description: 'Mixed salad with crispy pita chips.', price: 8.49, category: 'Salad' },
      { id: '20-7', name: 'Lamb Kebab', description: 'Grilled lamb skewers with rice.', price: 16.99, category: 'Main Course' },
      { id: '20-8', name: 'Labneh', description: 'Strained yogurt with olive oil.', price: 6.49, category: 'Appetizer' },
      { id: '20-9', name: 'Arabic Coffee', description: 'Traditional cardamom-spiced coffee.', price: 3.99, category: 'Drink' },
      { id: '20-10', name: 'Manakish', description: 'Flatbread with za\'atar and olive oil.', price: 7.49, category: 'Breakfast' },
    ],
  },
];
